name: Auto Merge Pull Request

on:
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  merge:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          python -m unittest discover -s tests

      - name: Check if contributor is a collaborator
        id: check_collaborator
        uses: actions/github-script@v6
        with:
          script: |
            const { data: collaborator } = await github.repos.checkCollaborator({
              owner: context.repo.owner,
              repo: context.repo.repo,
              username: context.payload.pull_request.user.login
            });
            return collaborator;
        continue-on-error: true

      - name: Fail if contributor is not a collaborator
        if: steps.check_collaborator.conclusion == 'failure'
        run: |
          echo "The contributor is not a collaborator. Failing..."
          exit 1

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Attempt automatic merge
        if: steps.check_collaborator.conclusion != 'failure'
        run: |
          git fetch origin +refs/pull/${{ github.event.pull_request.number }}/merge
          if git merge-base --is-ancestor FETCH_HEAD HEAD; then
            echo "No merge conflicts. Merging..."
            gh pr merge ${{ github.event.pull_request.number }} --merge --repo ${{ github.repository }}
          else
            echo "Merge conflicts found. Cannot auto-merge."
            exit 1
